export const localImages = {
  person1: require('../assets/person.png'),
  person2: require('../assets/person2.png'),
  person3: require('../assets/person3.png'),
  person4: require('../assets/person4.png'),
  person5: require('../assets/person5.png'),
  person6: require('../assets/person.png'),
  person7: require('../assets/person2.png'),
  person8: require('../assets/person3.png'),
  person9: require('../assets/person4.png'),
  person10: require('../assets/person5.png'),
  person11: require('../assets/person.png'),
  person12: require('../assets/person2.png'),
  person13: require('../assets/person3.png'),
  person14: require('../assets/person4.png'),
  person15: require('../assets/person5.png'),
  person16: require('../assets/person.png'),
  person17: require('../assets/person2.png'),
  person18: require('../assets/person3.png'),
  person19: require('../assets/person4.png'),
  person20: require('../assets/person5.png'),
};
